# 關於各區補習班的問題

## 前置作業

### 1. 先讀入相關資料，擷取需要的部分

In [67]:
import pandas as pd

df = pd.read_csv('Tainan.csv')

df.head()

,縣市,行政區別,總計,文理類合計,文理類[文理],文理類[外語],文理類[法政],技藝類合計,技藝類[電機_汽車修護_建築_工藝_製圖類],技藝類[資訊],技藝類[家政_插花烹飪],技藝類[縫紉],技藝類[美容_美髮_理髮],技藝類[音樂_舞蹈],技藝類[美術_書法_攝影_美工設計_圍棋],技藝類[心算_珠算_會計],技藝類[瑜珈],技藝類[速讀],技藝類[其他]
0,台南市,新營區,66,58,49,9,-,8,-,-,-,-,-,5,2,1,-,-,-
1,台南市,鹽水區,6,6,5,1,-,-,-,-,-,-,-,-,-,-,-,-,-
2,台南市,白河區,10,10,9,1,-,-,-,-,-,-,-,-,-,-,-,-,-
3,台南市,柳營區,5,5,4,1,-,-,-,-,-,-,-,-,-,-,-,-,-
4,台南市,後壁區,2,2,-,2,-,-,-,-,-,-,-,-,-,-,-,-,-

In [68]:
temp = df[['縣市','行政區別', '文理類合計']]
temp

     縣市 行政區別 文理類合計
0   台南市  新營區    58
1   台南市  鹽水區     6
2   台南市  白河區    10
3   台南市  柳營區     5
4   台南市  後壁區     2
5   台南市  東山區     2
6   台南市  麻豆區    27
7   台南市  下營區     8
8   台南市  六甲區    13
9   台南市  官田區     7
10  台南市  大內區     1
11  台南市  佳里區    48
12  台南市  學甲區    10
13  台南市  西港區    12
14  台南市  七股區     2
15  台南市  將軍區     3
16  台南市  北門區    -
17  台南市  新化區    32
18  台南市  善化區    33
19  台南市  新市區    35
20  台南市  安定區    13
21  台南市  山上區     3
22  台南市  玉井區    10
23  台南市  楠西區     2
24  台南市  南化區     1
25  台南市  左鎮區    -
26  台南市  仁德區    22
27  台南市  歸仁區    42
28  台南市  關廟區    10
29  台南市  龍崎區    -
30  台南市  永康區   190
31  台南市   東區   236
32  台南市   南區    59
33  台南市   北區   115
34  台南市  安南區   116
35  台南市  安平區    61
36  台南市  中西區    86

In [69]:
Type = temp.groupby(['行政區別'])['文理類合計'].sum().reset_index()

In [70]:
Type['縣市'] = '台南市'
Type

   行政區別 文理類合計   縣市
0   七股區     2  台南市
1   下營區     8  台南市
2   中西區    86  台南市
3   仁德區    22  台南市
4   佳里區    48  台南市
5   六甲區    13  台南市
6    北區   115  台南市
7   北門區    -   台南市
8   南化區     1  台南市
9    南區    59  台南市
10  善化區    33  台南市
11  大內區     1  台南市
12  學甲區    10  台南市
13  安南區   116  台南市
14  安定區    13  台南市
15  安平區    61  台南市
16  官田區     7  台南市
17  將軍區     3  台南市
18  山上區     3  台南市
19  左鎮區    -   台南市
20  後壁區     2  台南市
21  新化區    32  台南市
22  新市區    35  台南市
23  新營區    58  台南市
24   東區   236  台南市
25  東山區     2  台南市
26  柳營區     5  台南市
27  楠西區     2  台南市
28  歸仁區    42  台南市
29  永康區   190  台南市
30  玉井區    10  台南市
31  白河區    10  台南市
32  西港區    12  台南市
33  關廟區    10  台南市
34  鹽水區     6  台南市
35  麻豆區    27  台南市
36  龍崎區    -   台南市

In [71]:
dfm = pd.read_csv('mazhu.csv')

In [72]:
mazhu = dfm[['行政區別', '文理類合計']].groupby(['行政區別'])['文理類合計'].sum().reset_index()

In [73]:
mazhu['縣市'] = '馬祖縣'

In [74]:
mazhu

  行政區別 文理類合計   縣市
0  北竿鄉     -  馬祖縣
1  南竿鄉     3  馬祖縣
2  東引鄉     -  馬祖縣
3  莒光鄉     -  馬祖縣

In [78]:
dft = pd.read_csv('new Taipei.csv')
dft

     縣市 行政區別 文理類合計 技藝類合計   總計
0   新北市  烏來區     -     -    -
1   新北市  三峽區    71    33  104
2   新北市  坪林區     -     -    -
3   新北市  雙溪區     2     0    2
4   新北市  石碇區     -     -    -
5   新北市  新店區    96    66  162
6   新北市  貢寮區     2     0    2
7   新北市  平溪區     -     -    -
8   新北市  汐止區    83    34  117
9   新北市  瑞芳區     5     3    8
10  新北市  淡水區    99    33  132
11  新北市  三芝區     8     3   11
12  新北市  萬里區     1     1    2
13  新北市  林口區    92    34  126
14  新北市  石門區     -     -    -
15  新北市  金山區     8     3   11
16  新北市  八里區    20     3   23
17  新北市  五股區    31    12   43
18  新北市  樹林區    94    31  125
19  新北市  土城區   100    53  153
20  新北市  板橋區   320   159  479
21  新北市  鶯歌區    33    15   48
22  新北市  深坑區    13     1   14
23  新北市  中和區   138    51  189
24  新北市  新莊區   275    93  368
25  新北市  泰山區    48    12   60
26  新北市  三重區   191    79  270
27  新北市  蘆洲區   136    37  173
28  新北市  永和區   133    71  204

In [80]:
new = dft[['行政區別', '文理類合計']].groupby(['行政區別'])['文理類合計'].sum().reset_index()
new['縣市'] = '新北市'

In [82]:
new

   行政區別 文理類合計   縣市
0   三峽區    71  新北市
1   三芝區     8  新北市
2   三重區   191  新北市
3   中和區   138  新北市
4   五股區    31  新北市
5   八里區    20  新北市
6   土城區   100  新北市
7   坪林區     -  新北市
8   平溪區     -  新北市
9   新店區    96  新北市
10  新莊區   275  新北市
11  板橋區   320  新北市
12  林口區    92  新北市
13  樹林區    94  新北市
14  永和區   133  新北市
15  汐止區    83  新北市
16  泰山區    48  新北市
17  淡水區    99  新北市
18  深坑區    13  新北市
19  烏來區     -  新北市
20  瑞芳區     5  新北市
21  石碇區     -  新北市
22  石門區     -  新北市
23  萬里區     1  新北市
24  蘆洲區   136  新北市
25  貢寮區     2  新北市
26  金山區     8  新北市
27  雙溪區     2  新北市
28  鶯歌區    33  新北市

In [83]:
frames = [Type, mazhu, new]

result = pd.concat(frames)

In [84]:
result

   行政區別 文理類合計   縣市
0   七股區     2  台南市
1   下營區     8  台南市
2   中西區    86  台南市
3   仁德區    22  台南市
4   佳里區    48  台南市
..  ...   ...  ...
24  蘆洲區   136  新北市
25  貢寮區     2  新北市
26  金山區     8  新北市
27  雙溪區     2  新北市
28  鶯歌區    33  新北市

[70 rows x 3 columns]