# 關於各區補習班的問題

## 前置作業

### 1. 先讀入相關資料，擷取需要的部分

In [4]:
import pandas as pd

df = pd.read_csv('Tainan.csv')

df.head()

,縣市,行政區別,總計,文理類合計,文理類[文理],文理類[外語],文理類[法政],技藝類合計,技藝類[電機_汽車修護_建築_工藝_製圖類],技藝類[資訊],技藝類[家政_插花烹飪],技藝類[縫紉],技藝類[美容_美髮_理髮],技藝類[音樂_舞蹈],技藝類[美術_書法_攝影_美工設計_圍棋],技藝類[心算_珠算_會計],技藝類[瑜珈],技藝類[速讀],技藝類[其他]
0,台南市,新營區,66.0,58.0,49.0,9.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,5.0,2.0,1.0,NaN,NaN,NaN
1,台南市,鹽水區,6.0,6.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,台南市,白河區,10.0,10.0,9.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,台南市,柳營區,5.0,5.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,台南市,後壁區,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
temp = df[['縣市','行政區別', '文理類合計', '技藝類合計']]
temp

     縣市 行政區別  文理類合計  技藝類合計
0   台南市  新營區   58.0    8.0
1   台南市  鹽水區    6.0    NaN
2   台南市  白河區   10.0    NaN
3   台南市  柳營區    5.0    NaN
4   台南市  後壁區    2.0    NaN
5   台南市  東山區    2.0    NaN
6   台南市  麻豆區   27.0    NaN
7   台南市  下營區    8.0    1.0
8   台南市  六甲區   13.0    1.0
9   台南市  官田區    7.0    1.0
10  台南市  大內區    1.0    NaN
11  台南市  佳里區   48.0    6.0
12  台南市  學甲區   10.0    3.0
13  台南市  西港區   12.0    NaN
14  台南市  七股區    2.0    NaN
15  台南市  將軍區    3.0    NaN
16  台南市  北門區    NaN    NaN
17  台南市  新化區   32.0    3.0
18  台南市  善化區   33.0    1.0
19  台南市  新市區   35.0    2.0
20  台南市  安定區   13.0    1.0
21  台南市  山上區    3.0    NaN
22  台南市  玉井區   10.0    1.0
23  台南市  楠西區    2.0    1.0
24  台南市  南化區    1.0    NaN
25  台南市  左鎮區    NaN    NaN
26  台南市  仁德區   22.0    3.0
27  台南市  歸仁區   42.0    8.0
28  台南市  關廟區   10.0    1.0
29  台南市  龍崎區    NaN    NaN
30  台南市  永康區  190.0   17.0
31  台南市   東區  236.0   34.0
32  台南市   南區   59.0    4.0
33  台南市   北區  115.0   12.0
34  台南市  安南區  116.0    5.0
35  台南市  安平區   61.0    4.0
36  台南市  中西區   86.0   15.0

### 2. 篩選需要的資料，並嘗試讀出需要的樣子

In [6]:
Type = temp.groupby(['行政區別'])['文理類合計'].sum().reset_index()

In [7]:
Type['縣市'] = '台南市'
Type

   行政區別  文理類合計   縣市
0   七股區    2.0  台南市
1   下營區    8.0  台南市
2   中西區   86.0  台南市
3   仁德區   22.0  台南市
4   佳里區   48.0  台南市
5   六甲區   13.0  台南市
6    北區  115.0  台南市
7   北門區    0.0  台南市
8   南化區    1.0  台南市
9    南區   59.0  台南市
10  善化區   33.0  台南市
11  大內區    1.0  台南市
12  學甲區   10.0  台南市
13  安南區  116.0  台南市
14  安定區   13.0  台南市
15  安平區   61.0  台南市
16  官田區    7.0  台南市
17  將軍區    3.0  台南市
18  山上區    3.0  台南市
19  左鎮區    0.0  台南市
20  後壁區    2.0  台南市
21  新化區   32.0  台南市
22  新市區   35.0  台南市
23  新營區   58.0  台南市
24   東區  236.0  台南市
25  東山區    2.0  台南市
26  柳營區    5.0  台南市
27  楠西區    2.0  台南市
28  歸仁區   42.0  台南市
29  永康區  190.0  台南市
30  玉井區   10.0  台南市
31  白河區   10.0  台南市
32  西港區   12.0  台南市
33  關廟區   10.0  台南市
34  鹽水區    6.0  台南市
35  麻豆區   27.0  台南市
36  龍崎區    0.0  台南市

In [8]:
dfm = pd.read_csv('mazhu.csv')

In [9]:
mazhu = dfm[['行政區別', '文理類合計']].groupby(['行政區別'])['文理類合計'].sum().reset_index()

In [10]:
mazhu['縣市'] = '馬祖縣'

In [11]:
mazhu

  行政區別  文理類合計   縣市
0  北竿鄉    0.0  馬祖縣
1  南竿鄉    3.0  馬祖縣
2  東引鄉    0.0  馬祖縣
3  莒光鄉    0.0  馬祖縣

In [47]:
dft = pd.read_csv('new Taipei.csv')
dft

     縣市 行政區別  文理類合計  技藝類合計     總計
0   新北市  烏來區    NaN    NaN    NaN
1   新北市  三峽區   71.0   33.0  104.0
2   新北市  坪林區    NaN    NaN    NaN
3   新北市  雙溪區    2.0    0.0    2.0
4   新北市  石碇區    NaN    NaN    NaN
5   新北市  新店區   96.0   66.0  162.0
6   新北市  貢寮區    2.0    0.0    2.0
7   新北市  平溪區    NaN    NaN    NaN
8   新北市  汐止區   83.0   34.0  117.0
9   新北市  瑞芳區    5.0    3.0    8.0
10  新北市  淡水區   99.0   33.0  132.0
11  新北市  三芝區    8.0    3.0   11.0
12  新北市  萬里區    1.0    1.0    2.0
13  新北市  林口區   92.0   34.0  126.0
14  新北市  石門區    NaN    NaN    NaN
15  新北市  金山區    8.0    3.0   11.0
16  新北市  八里區   20.0    3.0   23.0
17  新北市  五股區   31.0   12.0   43.0
18  新北市  樹林區   94.0   31.0  125.0
19  新北市  土城區  100.0   53.0  153.0
20  新北市  板橋區  320.0  159.0  479.0
21  新北市  鶯歌區   33.0   15.0   48.0
22  新北市  深坑區   13.0    1.0   14.0
23  新北市  中和區  138.0   51.0  189.0
24  新北市  新莊區  275.0   93.0  368.0
25  新北市  泰山區   48.0   12.0   60.0
26  新北市  三重區  191.0   79.0  270.0
27  新北市  蘆洲區  136.0   37.0  173.0
28  新北市  永和區  133.0   71.0  204.0

In [48]:
new = dft[['行政區別', '文理類合計']].groupby(['行政區別'])['文理類合計'].sum().reset_index()
new['縣市'] = '新北市'

In [49]:
new

   行政區別  文理類合計   縣市
0   三峽區   71.0  新北市
1   三芝區    8.0  新北市
2   三重區  191.0  新北市
3   中和區  138.0  新北市
4   五股區   31.0  新北市
5   八里區   20.0  新北市
6   土城區  100.0  新北市
7   坪林區    0.0  新北市
8   平溪區    0.0  新北市
9   新店區   96.0  新北市
10  新莊區  275.0  新北市
11  板橋區  320.0  新北市
12  林口區   92.0  新北市
13  樹林區   94.0  新北市
14  永和區  133.0  新北市
15  汐止區   83.0  新北市
16  泰山區   48.0  新北市
17  淡水區   99.0  新北市
18  深坑區   13.0  新北市
19  烏來區    0.0  新北市
20  瑞芳區    5.0  新北市
21  石碇區    0.0  新北市
22  石門區    0.0  新北市
23  萬里區    1.0  新北市
24  蘆洲區  136.0  新北市
25  貢寮區    2.0  新北市
26  金山區    8.0  新北市
27  雙溪區    2.0  新北市
28  鶯歌區   33.0  新北市

### 3. 運用Frame把三份整理好的資料串在一起

In [50]:
frames = [Type, mazhu, new]

result = pd.concat(frames)

In [51]:
result

   行政區別  文理類合計   縣市
0   七股區    2.0  台南市
1   下營區    8.0  台南市
2   中西區   86.0  台南市
3   仁德區   22.0  台南市
4   佳里區   48.0  台南市
..  ...    ...  ...
24  蘆洲區  136.0  新北市
25  貢寮區    2.0  新北市
26  金山區    8.0  新北市
27  雙溪區    2.0  新北市
28  鶯歌區   33.0  新北市

[70 rows x 3 columns]

## 問題階段

### Q1. 三個縣市各有多少間文理類補習班?

In [52]:
cram_counts = result['縣市'].value_counts()
cram_counts

台南市    37
新北市    29
馬祖縣     4
Name: 縣市, dtype: int64

### Q2. 新北市最多補習班的區域是?

In [101]:
new["縣市"] = '新北市'
largest_areas = new.loc[new["縣市"] == '新北市', ["行政區別", "文理類合計"]].nlargest(1, "文理類合計")
print(largest_areas)

   行政區別  文理類合計
11  板橋區  320.0

### Q3. 台南市最多補習班的區域是?

In [103]:
Type["縣市"] = '台南市'
largest_areas = Type.loc[Type["縣市"] == '台南市', ["行政區別", "文理類合計"]].nlargest(1, "文理類合計")
print(largest_areas)

   行政區別  文理類合計
24   東區  236.0

### Q4. 新北市有哪些區有超過100間補習班?

In [62]:
new.loc[new['文理類合計'] > 100]

   行政區別  文理類合計   縣市
2   三重區  191.0  新北市
3   中和區  138.0  新北市
10  新莊區  275.0  新北市
11  板橋區  320.0  新北市
14  永和區  133.0  新北市
24  蘆洲區  136.0  新北市

### Q5. 台南市有那些區有超過100間補習班?

In [63]:
Type.loc[Type['文理類合計'] > 100]

   行政區別  文理類合計   縣市
6    北區  115.0  台南市
13  安南區  116.0  台南市
24   東區  236.0  台南市
29  永康區  190.0  台南市

### Q6. 新北市有幾區少於5間補習班?

In [65]:
new.loc[new['文理類合計'] < 5]

   行政區別  文理類合計   縣市
7   坪林區    0.0  新北市
8   平溪區    0.0  新北市
19  烏來區    0.0  新北市
21  石碇區    0.0  新北市
22  石門區    0.0  新北市
23  萬里區    1.0  新北市
25  貢寮區    2.0  新北市
27  雙溪區    2.0  新北市

### Q7. 台南市有幾區少於5間補習班?

In [28]:
Type.loc[Type['文理類合計'] < 5]

   行政區別  文理類合計   縣市
0   七股區    2.0  台南市
7   北門區    0.0  台南市
8   南化區    1.0  台南市
11  大內區    1.0  台南市
17  將軍區    3.0  台南市
18  山上區    3.0  台南市
19  左鎮區    0.0  台南市
20  後壁區    2.0  台南市
25  東山區    2.0  台南市
27  楠西區    2.0  台南市
36  龍崎區    0.0  台南市

### Q8. 馬祖縣的補習班一間平均有多少學生?(馬祖縣國中小+高中學生數= 704+235 = 939)

In [79]:
students = 939
total_tuition = mazhu['文理類合計'].sum()
average_students_per_class = students / total_tuition
print("馬祖補習班的平均學生數為:", average_students_per_class)

馬祖補習班的平均學生數為: 313.0

### Q9. 區域有超過100間補習班在3地(新北市、台南市、馬祖縣)的占比

In [40]:
result['文理類合計'] = result['文理類合計'].astype(int)
big = result.loc[result['文理類合計'] > 100]

In [41]:
counts = big['縣市'].value_counts()

proportions = counts / len(big)
formatted_proportions = proportions.apply(lambda x: '{:.2%}'.format(x))

print(formatted_proportions)

新北市    60.00%
台南市    40.00%
Name: 縣市, dtype: object

### Q10. 台南市補習班密度(假定補習班是平均分布的)

In [93]:
square = 2192000000   #平方公尺
tainan_tuition = Type['文理類合計'].sum()

In [94]:
tainan_tuition

1280.0

In [95]:
average_square_per_class = square / tainan_tuition

In [98]:
print("台南補習班的平均密度為:", average_square_per_class, "平方公尺/間")

台南補習班的平均密度為: 1712500.0 平方公尺/間